- hosts:
    - testing
    - produccion
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Ejecutar TP_INI
      import_role:
        name: TP_INI
    - name: Crear Roles
      import_role:
        name: crear_roles

    - name: Crear usuarios del grupo
      import_role:
        name: Alta_Usuarios_ayso_parcial

    - name: Configurar sudoers del grupo
      import_role:
        name: Sudoers_ayso_parcial

    - name: Instalar herramientas
      import_role:
        name: Instalar-tools_ayso_parcial

    - name: "Final"
      debug:
        msg: "Todos los roles fueron ejecutados correctamente."

